name: CI Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Bajar tu c√≥digo
    - uses: actions/checkout@v3

    # 2. Configurar Java 17
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Compilar el proyecto con Maven (crea el .jar)
    - name: Build & Test
      run: mvn clean package -DskipTests

    # 4. Construir la imagen Docker usando el archivo que creamos en el Paso 2
    - name: Build Docker image
      run: docker build -t myapp:latest .
