name: CI Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Bajar tu código
    - uses: actions/checkout@v3

    # 2. Configurar Java 17
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Compilar el proyecto con Maven
    - name: Build & Test
      run: mvn clean package -DskipTests

    # 4. VERIFICACIÓN (Paso extra de seguridad)
    # Este paso nos mostrará si el archivo .jar se creó correctamente
    - name: List files in target
      run: ls -la target/

    # 5. Construir la imagen Docker
    - name: Build Docker image
      run: docker build -t myapp:latest .
